# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStream',
            fields=[
                ('message_stream_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_timestamp', models.DateTimeField()),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
